name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./go-web-app
        run: go build -o myapp

      - name: Test
        working-directory: ./go-web-app
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GolangCI-Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: ./go-web-app
        

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}
  
  update-newtag-in-helm:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update new tag in Helm chart
        run: |
          sed -i "s/tag: .*/tag: '${{ github.run_id }}'/" helm/go-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "ariefshaik001@gmail.com"
          git config --local user.name "ariefshaik7"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update Helm chart"
          git push